server:
  port: 8082
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/testKeystore.p12
    key-store-password: changeit
    require-ssl: true
  session:
    cookie:
      name: UISESSION
spring:
  thymeleaf:
    cache: false
  security:
    trust-all-certificates: true
    oauth2:
      client:
        registration:
          custom-client:
            client-id: R2dpxQ3vPrtfgF72
            client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
            client-name: Auth Server
            scope: user_info
            provider: custom-provider
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            client-authentication-method: basic
            authorization-grant-type: authorization_code
          facebook:
            client-id: 578191556266322
            client-secret: e4631a34c631701866d7315281bc2b3d
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            scope:
              - email
              - public_profile
        provider:
          custom-provider:
            token-uri: https://localhost:8081/auth/oauth/token
            authorization-uri: https://localhost:8081/auth/oauth/authorize
            user-info-uri: https://localhost:8081/auth/user/me
            user-name-attribute: name
          facebook:
            token-uri: https://graph.facebook.com/v3.0/oauth/access_token
            authorization-uri: https://www.facebook.com/v3.0/dialog/oauth
            user-info-uri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified
            user-name-attribute: name
