server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/testKeystore.p12
    key-store-password: changeit
    key-alias: localhost
    require-ssl: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 571324953410235
            client-secret: 62cbb3cba93a913cd9ca0d4b09555b9a
            redirect-uri: "https://localhost:8443/login/oauth2/code/"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v3.0/dialog/oauth
            token-uri: https://graph.facebook.com/v3.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified