server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/testKeystore.p12
    key-store-password: changeit
    key-alias: localhost
    require-ssl: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    trust-all-certificates: true
    oauth2:
      client:
        registration:
          custom-client:
            client-id: R2dpxQ3vPrtfgF72
            client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
            provider: custom-provider
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: https://localhost:8081/auth/oauth/token
            authorization-uri: https://localhost:8081/auth/oauth/authorize
            user-info-uri: https://localhost:8081/auth/user/me
            user-name-attribute: name